# Generated by Django 2.1.1 on 2019-03-26 23:07

import Salmonella.models.projModels
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View_apcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Salmonella_view_apcc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('hasSnp', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file_location', models.FileField(max_length=500, upload_to='Alleles/')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='project name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('file_location', models.FileField(upload_to='References/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkId', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=140, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Web resource name')),
            ],
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, verbose_name='isolate name')),
                ('privacy_status', models.CharField(choices=[('PU', 'Public'), ('PV', 'Private')], max_length=2)),
                ('server_status', models.CharField(choices=[('U', 'Uploaded'), ('I', 'InQueue'), ('R', 'Running'), ('H', 'Holding'), ('C', 'Complete')], max_length=1)),
                ('assignment_status', models.CharField(blank=True, choices=[('A', 'Assigned'), ('F', 'Failed: contamination'), ('G', 'Failed: genome quality'), ('S', 'Failed: serovar incompatibility'), ('E', 'Error: other')], max_length=1, null=True)),
                ('file_forward', models.FileField(blank=True, max_length=500, null=True, upload_to=Salmonella.models.projModels.isolateUploadPath)),
                ('file_reverse', models.FileField(blank=True, max_length=500, null=True, upload_to=Salmonella.models.projModels.isolateUploadPath)),
                ('file_alleles', models.FileField(blank=True, max_length=500, null=True, upload_to=Salmonella.models.projModels.isolateUploadPath)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('extFks', models.ManyToManyField(to='Salmonella.ExternalFks')),
            ],
        ),
        migrations.CreateModel(
            name='Isolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('disease', models.CharField(blank=True, max_length=120, null=True, verbose_name='Host disease')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Collection date')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Collection year')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State or sub country')),
                ('postcode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_location', models.IntegerField()),
                ('end_location', models.IntegerField()),
                ('orientation', models.CharField(choices=[('+', 'Forward'), ('-', 'Reverse')], max_length=1)),
                ('locus_type', models.CharField(blank=True, choices=[('GN', 'Gene'), ('PS', 'Pseudogene'), ('IG', 'Intergenic'), ('PR', 'Promoter'), ('OT', 'Other')], max_length=2, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('chromosome', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='Mgt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='project name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Organism short name')),
                ('organism', models.CharField(max_length=100, verbose_name='Organism scientific name')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uncertainty_threshold', models.IntegerField(verbose_name='limit on number of genes == 0')),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('loci', models.ManyToManyField(to='Salmonella.Locus')),
            ],
        ),
        migrations.CreateModel(
            name='Snp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='with regards to allele seq.')),
                ('original_aa', models.CharField(choices=[('A', 'Adenine'), ('C', 'Cytosine'), ('G', 'Guanine'), ('T', 'Thymine'), ('N', 'Unidentified')], max_length=1)),
                ('altered_aa', models.CharField(choices=[('A', 'Adenine'), ('C', 'Cytosine'), ('G', 'Guanine'), ('T', 'Thymine'), ('N', 'Unidentified')], max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tables_ap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField()),
                ('table_name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Tables_cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('display_table', models.IntegerField(verbose_name='table to display it in')),
                ('display_order', models.IntegerField(verbose_name='order of display in display_table')),
                ('display_name', models.CharField(max_length=50)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together={('position', 'original_aa', 'altered_aa')},
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salmonella.User'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('continent', 'country', 'state', 'postcode')},
        ),
        migrations.AlterUniqueTogether(
            name='isolation',
            unique_together={('source', 'type', 'host', 'disease', 'date', 'year')},
        ),
        migrations.AddField(
            model_name='isolate',
            name='isolation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Isolation'),
        ),
        migrations.AddField(
            model_name='isolate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Location'),
        ),
        migrations.AddField(
            model_name='isolate',
            name='mgt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Mgt'),
        ),
        migrations.AddField(
            model_name='isolate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salmonella.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='externalfks',
            unique_together={('fkId', 'name')},
        ),
        migrations.AddField(
            model_name='chromosome',
            name='reference',
            field=models.ForeignKey(on_delete='PROTECT', to='Salmonella.Reference'),
        ),
        migrations.AddField(
            model_name='analysis_project',
            name='isolates',
            field=models.ManyToManyField(to='Salmonella.Isolate'),
        ),
        migrations.AddField(
            model_name='analysis_project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salmonella.User'),
        ),
        migrations.AddField(
            model_name='allele',
            name='locus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salmonella.Locus'),
        ),
        migrations.AddField(
            model_name='allele',
            name='snps',
            field=models.ManyToManyField(to='Salmonella.Snp'),
        ),
        migrations.AlterUniqueTogether(
            name='tables_cc',
            unique_together={('scheme', 'display_table', 'display_order')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='isolate',
            unique_together={('project', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='allele',
            unique_together={('identifier', 'locus')},
        ),
    ]
