# Generated by Django 2.1.1 on 2019-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salmonella', '0002_auto_20190327_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables_ap',
            name='display_name',
            field=models.CharField(default='blah blah', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='isolate',
            name='server_status',
            field=models.CharField(choices=[('U', 'Uploaded'), ('I', 'InQueue'), ('R', 'Running'), ('H', 'Holding'), ('C', 'Complete'), ('D', 'ToDownload')], max_length=1),
        ),
    ]
