# Generated by Django 2.1.1 on 2019-06-13 02:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Salmonella', '0003_auto_20190516_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ap8_0',
            old_name='STMMW15261',
            new_name='STMMW00011',
        ),
        migrations.RenameField(
            model_name='ap8_0',
            old_name='STMMW15321',
            new_name='STMMW06021',
        ),
        migrations.RenameField(
            model_name='ap8_0',
            old_name='STMMW15331',
            new_name='STMMW07931',
        ),
        migrations.RenameField(
            model_name='ap8_1',
            old_name='STMMW30971',
            new_name='STMMW15261',
        ),
        migrations.RenameField(
            model_name='ap8_1',
            old_name='STMMW30981',
            new_name='STMMW15321',
        ),
        migrations.RenameField(
            model_name='ap8_1',
            old_name='STMMW30991',
            new_name='STMMW15331',
        ),
        migrations.RenameField(
            model_name='ap8_1',
            old_name='STMMW31001',
            new_name='STMMW21031',
        ),
        migrations.RenameField(
            model_name='ap8_1',
            old_name='STMMW31021',
            new_name='STMMW24061',
        ),
        migrations.RenameField(
            model_name='ap9_1',
            old_name='STMMW08421',
            new_name='STMMW00011',
        ),
        migrations.RenameField(
            model_name='ap9_1',
            old_name='STMMW08431',
            new_name='STMMW06021',
        ),
        migrations.RenameField(
            model_name='ap9_1',
            old_name='STMMW08441',
            new_name='STMMW07931',
        ),
        migrations.RenameField(
            model_name='ap9_2',
            old_name='STMMW18551',
            new_name='STMMW08421',
        ),
        migrations.RenameField(
            model_name='ap9_2',
            old_name='STMMW18561',
            new_name='STMMW08431',
        ),
        migrations.RenameField(
            model_name='ap9_2',
            old_name='STMMW18561STMMW18571',
            new_name='STMMW08441',
        ),
        migrations.RenameField(
            model_name='ap9_3',
            old_name='STMMW30891STM3130',
            new_name='STMMW18551',
        ),
        migrations.RenameField(
            model_name='ap9_3',
            old_name='STMMW30921',
            new_name='STMMW18561',
        ),
        migrations.RenameField(
            model_name='ap9_3',
            old_name='STMMW30931',
            new_name='STMMW18561STMMW18571',
        ),
        migrations.RenameField(
            model_name='ap9_3',
            old_name='STMMW30931STMMW30941',
            new_name='STMMW21031',
        ),
        migrations.RenameField(
            model_name='ap9_3',
            old_name='STMMW30941',
            new_name='STMMW24061',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41731',
            new_name='STMMW30891STM3130',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41741',
            new_name='STMMW30921',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41751',
            new_name='STMMW30931',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41761',
            new_name='STMMW30931STMMW30941',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41771',
            new_name='STMMW30941',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41781',
            new_name='STMMW38221',
        ),
        migrations.RenameField(
            model_name='ap9_4',
            old_name='STMMW41791',
            new_name='STMMW39081',
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW30971',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW30981',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW30991',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW31001',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW31021',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW38221',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap8_2',
            name='STMMW39081',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41731',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41741',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41751',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41761',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41771',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41781',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap9_5',
            name='STMMW41791',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allele',
            name='file_location',
            field=models.FileField(max_length=500, upload_to='..srv/scratch/lanlab/mgtdb/Alleles/'),
        ),
        migrations.AlterField(
            model_name='chromosome',
            name='file_location',
            field=models.FileField(upload_to='..srv/scratch/lanlab/mgtdb/References/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='continent',
            field=models.CharField(blank=True, choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Oceania', 'Oceania'), ('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Asia', 'Asia')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
