# Generated by Django 2.1.1 on 2019-06-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salmonella', '0008_auto_20190618_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allele',
            name='file_location',
            field=models.FileField(max_length=500, upload_to='Alleles/'),
        ),
        migrations.AlterField(
            model_name='chromosome',
            name='file_location',
            field=models.FileField(upload_to='References/'),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='assignment_status',
            field=models.CharField(blank=True, choices=[('A', 'Assigned MGT'), ('F', 'Failed: contamination'), ('G', 'Failed: genome quality'), ('S', 'Failed: serovar incompatibility'), ('E', 'Error: other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='isolate',
            name='server_status',
            field=models.CharField(choices=[('U', 'Uploaded reads'), ('V', 'Uploaded alleles'), ('I', 'InQueue'), ('R', 'Running reads to alleles'), ('S', 'Running alleles to MGT'), ('H', 'Holding'), ('C', 'Complete'), ('D', 'To download NCBI reads')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='view_apcc',
            table='Salmonella_view_apcc',
        ),
    ]
